name: Gradle Build with PostgreSQL

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres # PostgreSQL user for the database
          POSTGRES_PASSWORD: grouptenpsql       # PostgreSQL password
          POSTGRES_DB: GameShop           # PostgreSQL database name
        ports:
          - 5432:5432                   # Expose PostgreSQL port
        options: >-
          --health-cmd "pg_isready -U test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./GameShop/gradlew

      - name: Run Gradle build
        run: ./GameShop/gradlew clean build

      - name: Run Gradle tests
        run: ./GameShop/gradlew test
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/testdb
          SPRING_DATASOURCE_USERNAME: test
          SPRING_DATASOURCE_PASSWORD: test
